

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;


public class Mainwin extends javax.swing.JFrame {

DefaultTableModel  dlm;
ResultSet rs, rs1,rs2;





    public Mainwin() {
        initComponents();
        web.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        
        
        dlm = (DefaultTableModel) tbl.getModel();
        try 
        {
            Class.forName("com.mysql.jdbc.Driver");
    Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/password_manager","root","tiger");
    Statement stmt = (Statement) con.createStatement();
    String query = "select * from "+variables.username+" ;";
    rs = stmt.executeQuery(query);
    while(rs.next())
    {
        String un = rs.getString("USERNAME");
        String pass = rs.getString("PASSWORD");
        String url = rs.getString("URL");
        String comm = rs.getString("COMMENTS");
        dlm.addRow(new Object[] {un,pass,url,comm});
        
    } 
    Statement stmt1 = (Statement) con.createStatement();
    String query1 = "select * from users where Username = '"+variables.username+"';"; 
    rs1 = stmt1.executeQuery(query1);
    while(rs1.next())
    {
        String na = rs1.getString("Name");
       String ld = rs1.getString("Created");
        lblname.setText(na);
        lblcreated.setText(ld);
    } 
        
    

        }
        catch (Exception e)
        {
            System.out.println("error");
        }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jButton1 = new javax.swing.JButton();
        adduser = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        switchuser = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblcreated = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        web = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        jMenu10.setText("jMenu10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arvirant Password Manager");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepack/Actions-contact-new-icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        adduser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepack/Actions-list-add-user-icon.png"))); // NOI18N
        adduser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adduserMouseEntered(evt);
            }
        });
        adduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adduserActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepack/Actions-list-remove-user-icon.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepack/Actions-draw-eraser-icon.png"))); // NOI18N
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        switchuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepack/Apps-system-users-icon.png"))); // NOI18N
        switchuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchuserActionPerformed(evt);
            }
        });

        tree.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categories", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 1, 12)));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Password Manager");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Web");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Application");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Credit Cards");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Others");
        treeNode1.add(treeNode2);
        tree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        tree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                treeValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(tree);
        tree.getAccessibleContext().setAccessibleName("");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "WELCOME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setText("Name          :");

        jLabel2.setText("Time            :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblname, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcreated, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcreated, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No.", "Item Name", "Item Code", "Price", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        lbl1.setBackground(new java.awt.Color(250, 251, 202));
        lbl1.setText("Add Item");
        lbl1.setOpaque(true);

        lbl2.setBackground(new java.awt.Color(250, 251, 202));
        lbl2.setText("Delete Item");
        lbl2.setOpaque(true);

        lbl3.setBackground(new java.awt.Color(250, 251, 202));
        lbl3.setText("Modify");
        lbl3.setOpaque(true);

        lbl4.setBackground(new java.awt.Color(250, 251, 202));
        lbl4.setText("Details");
        lbl4.setOpaque(true);

        web.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepack/temp url.PNG"))); // NOI18N
        web.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                webMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                webMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                webMouseReleased(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 251, 202));
        jLabel4.setText("Print");

        jLabel5.setBackground(new java.awt.Color(255, 251, 202));
        jLabel5.setText("Options");

        jMenu1.setText("File");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepack/Button-Turn-Off-icon.png"))); // NOI18N
        jMenuItem2.setText("Log Off");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepack/Actions-dialog-close-icon.png"))); // NOI18N
        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu12.setText("View");

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepack/Office-Customer-Male-Light-icon.png"))); // NOI18N
        jMenuItem7.setText("Tables");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem7);

        jMenuBar1.add(jMenu12);

        jMenu11.setText("Tools");

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepack/Apps-system-users-icon1.png"))); // NOI18N
        jMenuItem8.setText("Switch To Billing");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem8);

        jMenuItem1.setText("Options");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem1);

        jMenuBar1.add(jMenu11);

        jMenu5.setText("Help");

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepack/About-icon.png"))); // NOI18N
        jMenuItem9.setText("About");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adduser, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(switchuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addComponent(web))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adduser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(web, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(switchuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl1)
                            .addComponent(lbl2)
                            .addComponent(lbl3)
                            .addComponent(lbl4)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void treeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_treeValueChanged
        int x =  tree.getMinSelectionRow(); 
        int r = dlm.getRowCount();
        System.out.println(""+x);
        int i; 
        
                if (x==0)
        {
            dlm = (DefaultTableModel) tbl.getModel();
            for (i=0;i<r;i++)
            {
                dlm.removeRow(0);
            }
        try 
        {
            
            Class.forName("com.mysql.jdbc.Driver");
    Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/password_manager","root","tiger");
    Statement stmt5 = (Statement) con.createStatement();
    String query5 = "select * from "+variables.username+" ;";
    rs = stmt5.executeQuery(query5);
    while(rs.next())
    {
        String un = rs.getString("USERNAME");
        String pass = rs.getString("PASSWORD");
        String url = rs.getString("URL");
        String comm = rs.getString("COMMENTS");
        dlm.addRow(new Object[] {un,pass,url,comm});
        
    }
        }
        catch (Exception e)
        {
            System.out.println("error");
        }
        
        }
   
        
        
        if (x==1)
        {
            dlm = (DefaultTableModel) tbl.getModel();
            for (i=0;i<r;i++)
            {
                dlm.removeRow(0);
            }
        try 
        {
            
            Class.forName("com.mysql.jdbc.Driver");
    Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/password_manager","root","tiger");
    Statement stmt = (Statement) con.createStatement();
    String query = "select * from "+variables.username+"  where TYPE = 'Web';";
    rs = stmt.executeQuery(query);
    while(rs.next())
    {
        String un = rs.getString("USERNAME");
        String pass = rs.getString("PASSWORD");
        String url = rs.getString("URL");
        String comm = rs.getString("COMMENTS");
        dlm.addRow(new Object[] {un,pass,url,comm});
        
    }
        }
        catch (Exception e)
        {
            System.out.println("error");
        }
        
        }
        
        if (x==2)
        {
            dlm = (DefaultTableModel) tbl.getModel();
            for (i=0;i<r;i++)
            {
                dlm.removeRow(0);
            }
        try 
        {
            
            Class.forName("com.mysql.jdbc.Driver");
    Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/password_manager","root","tiger");
    Statement stmt2 = (Statement) con.createStatement();
    String query2 = "select * from "+variables.username+"  where TYPE = 'Application';";
    rs = stmt2.executeQuery(query2);
    while(rs.next())
    {
        String un = rs.getString("USERNAME");
        String pass = rs.getString("PASSWORD");
        String url = rs.getString("URL");
        String comm = rs.getString("COMMENTS");
        dlm.addRow(new Object[] {un,pass,url,comm});
        
    }
        }
        catch (Exception e)
        {
            System.out.println("error");
        }
        
        }
        
        if (x==3)
        {
            dlm = (DefaultTableModel) tbl.getModel();
            for (i=0;i<r;i++)
            {
                dlm.removeRow(0);
            }
        try 
        {
            
            Class.forName("com.mysql.jdbc.Driver");
    Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/password_manager","root","tiger");
    Statement stmt3 = (Statement) con.createStatement();
    String query3 = "select * from "+variables.username+"  where TYPE = 'Credit Cards';";
    rs = stmt3.executeQuery(query3);
    while(rs.next())
    {
        String un = rs.getString("USERNAME");
        String pass = rs.getString("PASSWORD");
        String url = rs.getString("URL");
        String comm = rs.getString("COMMENTS");
        dlm.addRow(new Object[] {un,pass,url,comm});
        
    }
        }
        catch (Exception e)
        {
            System.out.println("error");
        }
        
        }
     
    if (x==4)
        {
            dlm = (DefaultTableModel) tbl.getModel();
            for (i=0;i<r;i++)
            {
                dlm.removeRow(0);
            }
        try 
        {
            
            Class.forName("com.mysql.jdbc.Driver");
    Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/password_manager","root","tiger");
    Statement stmt4 = (Statement) con.createStatement();
    String query4 = "select * from "+variables.username+"  where TYPE = 'Others';";
    rs = stmt4.executeQuery(query4);
    while(rs.next())
    {
        String un = rs.getString("USERNAME");
        String pass = rs.getString("PASSWORD");
        String url = rs.getString("URL");
        String comm = rs.getString("COMMENTS");
        dlm.addRow(new Object[] {un,pass,url,comm});
        
    }
        }
        catch (Exception e)
        {
            System.out.println("error");
        }
        
        }

        
        
        
        
    }//GEN-LAST:event_treeValueChanged

    private void adduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adduserActionPerformed
        new addnewuser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adduserActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        int ans = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this user?");
        if (ans == 0)
        {
             try 
        {
            Class.forName("com.mysql.jdbc.Driver");
java.sql.Connection con= (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/password_manager","root","tiger");
            Statement stmt=(Statement) con.createStatement();
            String query= "delete from users where Username = '"+variables.username+"';";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "User deleted.");
            Statement stmt2=(Statement) con.createStatement();
            String query2= "drop table "+variables.username+"";
            
            stmt2.executeUpdate(query2);
            new Loginwin().setVisible(true);
            this.dispose();        
        
        }
        catch (Exception e)
        {
            
        }
        }
        
        
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void webMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webMousePressed
      
       
    }//GEN-LAST:event_webMousePressed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
       int x;
       x = tbl.getSelectedRow();
       
        
       variables.url = (String) tbl.getValueAt(x, 2);
       variables.tbluname = (String) tbl.getValueAt(x, 0);
       variables.tblpass = (String) tbl.getValueAt(x, 1);
       variables.tblcom = (String) tbl.getValueAt(x, 3);
       System.out.println(variables.tbluname+variables.tblpass+variables.url+variables.tblcom);
       

       
    }//GEN-LAST:event_tblMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new addnewwin().setVisible(true);        
this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void webMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webMouseClicked
            
  
    }//GEN-LAST:event_webMouseClicked

    private void webMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webMouseReleased
        goWebsite(web);
        variables.q = true;
        
    }//GEN-LAST:event_webMouseReleased

    private void switchuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchuserActionPerformed
 new Switchuserwin().setVisible(true);
 this.dispose();
    }//GEN-LAST:event_switchuserActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
new about2().setVisible(true);
this.dispose();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try
        {
           Class.forName("com.mysql.jdbc.Driver");
java.sql.Connection con= (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/password_manager","root","tiger");
            Statement stmt=(Statement) con.createStatement();
            String query = "select now()";
            rs2=stmt.executeQuery(query);
            while(rs.next())
            {
               String ldate = rs2.getString("now()");
               Statement stmt2 = (Statement) con.createStatement();
            String query2 = "update users set Last_Login='"+ldate+"'";
                stmt2.executeUpdate(query2);
            }
            Statement stmt3= (Statement) con.createStatement();
            String query3="select * from users;";
        }
        catch (Exception e)
        {
            
        }
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
        new Loginwin().setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
      System.exit(0);       
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
new Tables().setVisible(true);
this.dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
switchuser.doClick();

    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
int ans = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this user?");
        if (ans == 0)
        {
        int x;
       x = tbl.getSelectedRow();
        }
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       new Options().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void adduserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adduserMouseEntered
     lbl1.setVisible(true);
     
    }//GEN-LAST:event_adduserMouseEntered
private void goWebsite(JLabel website) {
    if (variables.q)
    {
        website.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    Desktop.getDesktop().browse(new URI(variables.url));
                    variables.q=false;
                } catch (URISyntaxException | IOException ex) {
                    //It looks like there's a problem
                }
            }
        });
    }}
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        
        
        try {
            // Set System L&F
        UIManager.setLookAndFeel(
            UIManager.getSystemLookAndFeelClassName());
    } 
    catch (UnsupportedLookAndFeelException e) {
       // handle exception
    }
    catch (ClassNotFoundException e) {
       // handle exception
    }
    catch (InstantiationException e) {
       // handle exception
    }
    catch (IllegalAccessException e) {
       // handle exception
    }
        
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainwin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainwin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainwin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainwin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Mainwin().setVisible(true);
                
                
            }
        });
        
        
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton adduser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lblcreated;
    private javax.swing.JLabel lblname;
    private javax.swing.JButton switchuser;
    private javax.swing.JTable tbl;
    private javax.swing.JTree tree;
    private javax.swing.JLabel web;
    // End of variables declaration//GEN-END:variables
}
